### ISSUE TITLE
brew issue

### ISSUE THREAD

**Issue by professor** [pivotal/git-author#15]
I was installing git-author via brew and had an interesting experience.

I could see that brew was running both of the following lines
```
    system "touch ~/.git-author-template"
    system "git config --global commit.template ~/.git-author-template"
```
However, the file  ~/.git-author-template did not exist on the file system

I'm wondering if brew does not run as the current user. 

Any thoughts?

Cloning the repo and running setup.sh worked fine

**Comment by professor** [comment]
After upgrading to 1.0.2, I closed this too soon.  The file ~/.git-author-template did not exist on the file system.

**Comment by amilkh** [comment]
Looks like this solved it:
https://github.com/pivotal/git-author/commit/69fcc82cd4ab8033f6b625d9c85959762f559cff
