### ISSUE TITLE
unable to install automatically without pivotal org ssh keys

### ISSUE THREAD

**Issue by cwlbraa** [pivotal/git-author#18]
The CF CAPI team would love to use git-author, but we cannot automatically install it via Brewfile or by scripting because the permissions here require that one is logged in to the Pivotal org. 😢 We perform unattended installs and upgrades of our workspace machines, and would prefer for this to roll out to all of them simultaneously and automatically. 

Please make this public or fix the Brew formula. It'd be very much appreciated.

Thanks, and excited to be rid of git-duet! 🎉

**Comment by professor** [comment]
The brew tap downloads a tar.gz and then untars it. See https://github.com/pivotal-legacy/homebrew-tap/blob/master/git-author.rb 

I'll check out your Brewfile once I find your team's repo. I did a search for `capi` and had 0 search results. Discoverability fail. =(

pivotal/workstation-setup does the installation with a `brew install git-author` without requiring the user to authenticate.  https://github.com/pivotal/workstation-setup/blob/8e307518ce696d43df26f03914dd0e48e5895999/scripts/common/git.sh#L8

Given the way that the `https://github.com/pivotal` org is currently set up, if you use `git@github.com:pivotal/git-author.git`you will need to authenticate. Anyone can use `https://github.com/pivotal/git-author.git` to download the repo. If this is a problem, please let @onlyawave know

**Comment by cwlbraa** [comment]
We must've had some broken git config on Friday. Both Brew and `git clone https://github.com/pivotal/git-author.git` were requiring username/password authentication. Works fine today. Very strange. 

You can see the workspace here: https://github.com/cloudfoundry/capi-workspace . Added tags just now to make it more searchable.
