### ISSUE TITLE
clearer name for the template

### ISSUE THREAD

**Issue by cjcjameson** [pivotal/git-author#3]
Hi there, Xin and I were talking and we weren't able to come up with a better name for the template file. Right now, it's `~/.git-author` which is confusingly adjacent to `~/.git-authors` (from git-duet) or other similar files. We want a name that emphasizes that it's a transitory file: as you `git author ab cd`, this file changes (whereas other similarly named files are much more static).

**Leading idea: `~/.git-author.template`**, but other possible options are:
git-author-authors
git-author-message
git-author-template

**Comment by xinzweb** [comment]
Thanks a lot CJ. It's a good idea to change it to a different name, so that it won't be confused with other `.git*` files. I like `.git-author-template`. Let's fix it.
